[package]
name = "apas-ai"
version = "0.1.0"
edition = "2024"

[dependencies]
tree_collections = "0.1.8"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }



[lints.rust]
non_snake_case = "allow"
non_upper_case_globals = "allow"
unused_imports = "allow"
dead_code = "allow"

[workspace]
members = [ "." ]

[[bench]]
name = "BenchArraySeq"
harness = false

[[bench]]
name = "BenchMathSeq"
harness = false

## DoublyLinkedList benchmarks moved to src/attic

[[bench]]
name = "BenchAVLTreeSeq"
harness = false

[[bench]]
name = "BenchArraySeqEphemeral"
harness = false
## SharedSinglyLinkedList removed

[[bench]]
name = "BenchArraySeqPersistent"
harness = false

[[bench]]
name = "BenchAVLTreeSeqPersistent"
harness = false

## SinglyLinkedList benchmarks moved to src/attic
[[bench]]
name = "BenchSinglyLinkedListPersistent"
harness = false
