[package]
name = "apas-ai"
version = "0.1.0"
edition = "2024"

[dependencies]
tree_collections = "0.1.8"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[lints.rust]
non_snake_case = "allow"
non_upper_case_globals = "allow"
unused_imports = "allow"
dead_code = "allow"

[workspace]
members = [ "." ]

[[bench]]
name = "BenchArraySeqStEph"
harness = false

## DoublyLinkedList benchmarks moved to src/attic

[[bench]]
name = "BenchMathSeq"
harness = false

[[bench]]
name = "BenchAVLTreeSeqStPer"
harness = false
## SharedSinglyLinkedList removed

[[bench]]
name = "BenchArraySeqStEphChap18"
harness = false

[[bench]]
name = "BenchArraySeqStPer"
harness = false

[[bench]]
name = "BenchArraySeqStPerChap19"
harness = false

## SinglyLinkedList benchmarks moved to src/attic
[[bench]]
name = "BenchAVLTreeSeqStPerChap19"
harness = false

[[bench]]
name = "BenchAVLTreeSeqStPerChap18"
harness = false

[[bench]]
name = "BenchLinkedListStPer"
harness = false

[[bench]]
name = "BenchLinkedListStPerChap18"
harness = false

[[bench]]
name = "BenchLinkedListStPerChap19"
harness = false

[[bench]]
name = "BenchLinkedListStEph"
harness = false

[[bench]]
name = "BenchLinkedListStEphChap18"
harness = false

[[bench]]
name = "BenchLinkedListStEphChap19"
harness = false
[[bench]]
name = "BenchArraySeqStPerChap18"
harness = false

[[bench]]
name = "BenchArraySeqStEphChap19"
harness = false

[[bench]]
name = "BenchAVLTreeSeqStEph"
harness = false

[[bench]]
name = "BenchAVLTreeSeqStEphChap18"
harness = false

[[bench]]
name = "BenchAVLTreeSeqStEphChap19"
harness = false
