[package]
name = "apas-ai"
version = "0.1.0"
edition = "2024"

[dependencies]
tree_collections = "0.1.8"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[lints.rust]
non_snake_case = "allow"
non_upper_case_globals = "allow"
unused_imports = "allow"
dead_code = "allow"

[workspace]
members = [ "." ]

[[bench]]
name = "BenchArraySeqEph"
harness = false

## DoublyLinkedList benchmarks moved to src/attic

[[bench]]
name = "BenchMathSeq"
harness = false

[[bench]]
name = "BenchAVLTreeSeqPer"
harness = false
## SharedSinglyLinkedList removed

[[bench]]
name = "BenchArraySeqEphChap18"
harness = false

[[bench]]
name = "BenchArraySeqPer"
harness = false

[[bench]]
name = "BenchArraySeqPerChap19"
harness = false

## SinglyLinkedList benchmarks moved to src/attic
[[bench]]
name = "BenchAVLTreeSeqPerChap19"
harness = false

[[bench]]
name = "BenchAVLTreeSeqPerChap18"
harness = false

[[bench]]
name = "BenchLinkedListPer"
harness = false

[[bench]]
name = "BenchLinkedListPerChap18"
harness = false

[[bench]]
name = "BenchLinkedListPerChap19"
harness = false

[[bench]]
name = "BenchLinkedListEph"
harness = false

[[bench]]
name = "BenchLinkedListEphChap18"
harness = false

[[bench]]
name = "BenchLinkedListEphChap19"
harness = false
[[bench]]
name = "BenchArraySeqPerChap18"
harness = false

[[bench]]
name = "BenchArraySeqEphChap19"
harness = false

[[bench]]
name = "BenchAVLTreeSeqEph"
harness = false

[[bench]]
name = "BenchAVLTreeSeqEphChap18"
harness = false

[[bench]]
name = "BenchAVLTreeSeqEphChap19"
harness = false
